language: python

python:
  - "3.8"

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py makemigrations

script:
  - black --check .
  #- flake8 --max-line-length 99 --ignore=F401 .
  - coverage run --source=polls manage.py test

deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAV53JPCOWJGOUABFV
  secret_access_key: 5cdqFf06mTr7cgHt9O9BH2YqtWzMZBKgRYZilfCOG
  region: us-west-2
  app: mysite-polls
  env: https://us-west-2.console.aws.amazon.com/elasticbeanstalk/home?region=us-west-2#/applications
  bucket_name: minibus
  before_deploy:
    - export AWS_DEFAULT_REGION=us-east-1
  on:
    branch: main

after_script:
  - coveralls
