language: python

python:
  - "3.8"

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py makemigrations

script:
  - black --check .
  - flake8 --max-line-length 99 --ignore=F401 .
  - coverage run --source=polls manage.py test
  - coverage report

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "AKIAV53JPCOWOSLOIZ4I"
  secret_access_key:
    secure: "E67z9OTHUfv/4fYJwQcBvU4U5QkuJUnSQ1rifNNiJ"
  region: "us-east-1"
  app: "mysite-polls"
  env: "mysite-polls-dev"
  bucket_name: "minibus"

after_script:
  - coveralls
